### ISSUE TITLE
model caffe文件下的模型区别

### ISSUE THREAD

**Issue by shaniu00** [imistyrain/MTCNN#12]
想我下 caffe 下 
det1.caffemodel  
det2.caffemodel 
det3.caffemodel 
det4.caffemodel 
区别是啥 我用opencv4.5有可以直接用的吗

**Comment by imistyrain** [comment]
det1是PNet, det2是RNet, det3 是ONet，det4是LNet(本项目未使用).
你可以使用[Netron](https://github.com/lutzroeder/netron)查看他们的网络结构
对opencv版本没有要求，可能会因宏定义改变而有些报错，不过稍微改改就好了
