### ISSUE TITLE
mtcnn detect face very slow

### ISSUE THREAD

**Issue by vtn98** [imistyrain/MTCNN#20]
Hi @imistyrain 
Thanks your project. 
I run your project and see MTCNN detect face very slow (300-400ms). How to improve the speed of MTCNN?
Thank you.

**Comment by imistyrain** [comment]
Could you provide some more info?
such as on what device you are testing and how many faces in your image and your image size?
you can try to resize your image to a small one or set min_size a larger num from 12 to 40.

**Comment by vtn98** [comment]
I use device: oppo reno4
There is one face in my image, face size: 85
image size: (w, h) = (2160, 1080)
How should I resize the image?

**Comment by imistyrain** [comment]
Yes, the image is really big, reisze it to 640x480

**Comment by vtn98** [comment]
I'm afraid it will affect my face. Maybe the face is distorted...

**Comment by vtn98** [comment]
thank @imistyrain,
I run my oppo ok, but when I run detect on QUALCOMM F10, it is still slow (~200ms/image size: 640x480, min face size: 85)
What should I do now?

**Comment by imistyrain** [comment]
Since your device power is really limited, you should such try another model such as [libfacedetection](https://github.com/ShiqiYu/libfacedetection).

**Comment by vtn98** [comment]
I want to have landmarks, but I don't find them in the libfacedetection (mobile). Can you suggest to me some other libs? Thank you.

**Comment by imistyrain** [comment]
![libfacedetection](https://github.com/ShiqiYu/libfacedetection/raw/master/images/cnnresult.png)
libfacedetection can detect landmarks.
